services:
  gitback:
    container_name: gitback
    # For users outside mainland China, please use the ghcr.io mirror
    # image: ghcr.io/mmdjiji/gitback:latest
    image: docker.cnb.cool/mmdjiji/gitback:latest
    restart: unless-stopped
    volumes:
      - ./repos:/app/repos
      - ./config.yaml:/app/config.yaml:ro
    depends_on: []

  cgit:
    container_name: cgit
    # For users outside mainland China, please use the ghcr.io mirror
    # image: ghcr.io/mmdjiji/cgit:latest
    image: docker.cnb.cool/mmdjiji/cgit:latest
    restart: unless-stopped
    ports:
      - 8787:80
    volumes:
      - ./repos:/srv/git/:ro
    environment:
      - CGIT_TITLE=GitBack
      - CGIT_DESC=Git-based code backup system
      - ENABLE_GRAVATAR=true
      - CGIT_SECTION_FROM_STARTPATH=1
      # - CGIT_THEME=cgithub-auto
      # - BASIC_AUTH_USER=admin
      # - BASIC_AUTH_PASS=12345678
    depends_on:
      - gitback
